name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/social-media-backend  .
      - name: Publish Image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/social-media-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/social-media-backend:latest
      - name: Delete old container
        run: docker rm -f social-media-backend-container
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name social-media-backend-container \
          -e NODE_ENV=production \
          -e PORT=8000 \
          -e DATABASE_URI='${{ secrets.DATABASE_URI }}' \
          -e EXPIRES_IN='90d' \
          -e SECRET='${{ secrets.SECRET }}' \
          -e CLOUDINARY_CLOUD_NAME='${{ secrets.CLOUDINARY_CLOUD_NAME }}' \
          -e CLOUDINARY_API_KEY='${{ secrets.CLOUDINARY_API_KEY }}' \
          -e CLOUDINARY_API_SECRET='${{ secrets.CLOUDINARY_API_SECRET }}' \
          ${{ secrets.DOCKER_USERNAME }}/social-media-backend:latest
